import { motion, type Variants } from "framer-motion";
import { Users, FileText, Sparkles, Heart } from 'lucide-react';

interface Stat {
  icon: typeof Users;
  value: string;
  label: string;
  suffix: string;
  color: string;
  bgColor: string;
}

const stats: Stat[] = [
  {
    icon: Users,
    value: '12,500+',
    label: 'Active Users',
    suffix: 'and growing daily',
    color: 'text-indigo-600 dark:text-indigo-400',
    bgColor: 'bg-indigo-100 dark:bg-indigo-900/40',
  },
  {
    icon: FileText,
    value: '84,200+',
    label: 'Notes Created',
    suffix: 'ideas captured',
    color: 'text-purple-600 dark:text-purple-400',
    bgColor: 'bg-purple-100 dark:bg-purple-900/40',
  },
  {
    icon: Sparkles,
    value: '36,800+',
    label: 'AI Summaries',
    suffix: 'generated by AI',
    color: 'text-pink-600 dark:text-pink-400',
    bgColor: 'bg-pink-100 dark:bg-pink-900/40',
  },
  {
    icon: Heart,
    value: '98.7%',
    label: 'Satisfaction',
    suffix: 'user happiness rate',
    color: 'text-emerald-600 dark:text-emerald-400',
    bgColor: 'bg-emerald-100 dark:bg-emerald-900/40',
  },
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.12,
    },
  },
};

const itemVariants: Variants = {
  hidden: {
    opacity: 0,
    y: 30,
  },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.5,
      ease: "easeOut",
    },
  },
};

const StatsSection = () => {
  return (
    <section className="relative overflow-hidden bg-gradient-to-br from-indigo-50 via-white to-purple-50 px-4 pb-24 pt-36 sm:px-6 lg:px-8 dark:from-gray-950 dark:via-gray-900 dark:to-gray-950">
      {/* Background decoration */}
      <div className="pointer-events-none absolute inset-0 -z-10" aria-hidden="true">
        <div className="absolute left-1/2 top-1/2 h-80 w-80 -translate-x-1/2 -translate-y-1/2 rounded-full bg-indigo-100/30 blur-3xl dark:bg-indigo-900/10" />
      </div>

      <motion.div
        className="mx-auto max-w-7xl"
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: '-100px' }}
        variants={{
          hidden: { opacity: 0, y: 30 },
          visible: {
            opacity: 1,
            y: 0,
            transition: { duration: 0.7, ease: 'easeOut' },
          },
        }}
      >
        {/* Section Header */}
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl dark:text-white">
            Trusted by Thousands of{' '}
            <span className="bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
              Creators
            </span>
          </h2>
          <p className="mt-4 text-base leading-relaxed text-gray-500 sm:text-lg dark:text-gray-400">
            Our platform is growing fast. Here is a snapshot of what the NotePilot
            community has achieved together.
          </p>
        </div>

        {/* Stats Grid */}
        <motion.div
          className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-4"
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-50px' }}
        >
          {stats.map((stat) => {
            const Icon = stat.icon;
            return (
              <motion.div
                key={stat.label}
                variants={itemVariants}
                className="group relative rounded-2xl border border-gray-100 bg-white p-6 text-center shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-gray-200 hover:shadow-md dark:border-gray-800 dark:bg-gray-900 dark:hover:border-gray-700"
              >
                {/* Icon */}
                <div
                  className={`mx-auto mb-4 inline-flex h-12 w-12 items-center justify-center rounded-xl transition-transform duration-300 group-hover:scale-110 ${stat.bgColor}`}
                >
                  <Icon className={`h-6 w-6 ${stat.color}`} />
                </div>

                {/* Value */}
                <p className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl dark:text-white">
                  {stat.value}
                </p>

                {/* Label */}
                <p className="mt-1.5 text-sm font-medium text-gray-700 dark:text-gray-300">
                  {stat.label}
                </p>

                {/* Suffix */}
                <p className="mt-1 text-xs text-gray-400 dark:text-gray-500">
                  {stat.suffix}
                </p>
              </motion.div>
            );
          })}
        </motion.div>
      </motion.div>
    </section>
  );
};

export default StatsSection;